configured_endpoints: 8
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/angel-kids-ai%2Fstreaming-availability-16fa35a29f15980bc6616275ae551c830263e36bddb98f1a2c01ff37461ed215.yml
